# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/VScode/course/ca-lab/prj3/exp10/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/div_gen_unsigned/div_gen_unsigned.xci
# IP: The module: 'div_gen_unsigned' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VScode/course/ca-lab/prj3/exp10/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/div_gen_unsigned/div_gen_unsigned_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_unsigned'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/VScode/course/ca-lab/prj3/exp10/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/div_gen_unsigned/div_gen_unsigned.xci
# IP: The module: 'div_gen_unsigned' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VScode/course/ca-lab/prj3/exp10/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/div_gen_unsigned/div_gen_unsigned_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_unsigned'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
